### ISSUE TITLE
Issue with navigation bar

### ISSUE THREAD

**Issue by easebuzz** [Tahir91/InshortView#2]
Once I set a navigation bar to InshortViewController, still, the collection view starts to scroll from 0 positions.
Can you suggest what changes do with the navigation bar?
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-09 at 01 05 43](https://user-images.githubusercontent.com/17761875/72009860-bc9d9980-327c-11ea-9a7d-43311ce2ec5b.png)

**Comment by SwiftCrew** [comment]
Fixed, Download again check collectionView property.

**Comment by pavanjadhav1412** [comment]
Could you please share name of the property and its value with navigation bar?
